CREATE TABLE IF NOT EXISTS  SUPER_HERO  (
  ID  int PRIMARY KEY,
  AGE int NOT NULL,
  CAN_FLY BOOLEAN  NOT NULL,
  NAME  varchar(255),
  NAME_POWER varchar(255),
  PROFESSION varchar(255),
  SUPER_NAME varchar(255),
  WORLD_NAMEB_BORN  varchar(255)

); 