--INSERT INTO SUPER_HERO (ID,AGE,CAN_FLY,NAME,NAME_POWER,PROFESSION,SUPER_NAME,WORLD_NAMEB_BORN) VALUES(1,20,TRUE,'clark ken','homnbre hierro','periodista','superman','marte');
--INSERT INTO SUPER_HERO (ID,AGE,CAN_FLY,NAME,NAME_POWER,PROFESSION,SUPER_NAME,WORLD_NAMEB_BORN) VALUES(2,21,FALSE,'peter parker','homnbre araña','fotografo','spiderman','tierra');
